manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: dccb09599635bdff17633fa7e9dab014b91dce90
      import: true

  self:
    path: zephcore
