manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 4e75d174842502495bdf2db17334bc1549e8d05f
      import: true

  self:
    path: zephcore
