manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 4658d2a31eb2911ba3b290b229085f2001c9bf0a
      import: true

  self:
    path: zephcore
